### PR TITLE
Fixes #48 - Support 'Run Action' against vRO 7.6 and vRO 8

### LINKED ISSUE #48: vRO 7.6  "vRealize Run Action" does not works
Performing "vRealize Run Action" in vRO 7.6 throws the following error:

Error:
# Running constants.js
# Execution ID: 077cc5c5-877b-41ee-a645-390047b1c044

# An error occurred: 405 - "<!doctype html><html lang=\"en\"><head><title>HTTP Status 405 – Method Not Allowed</title><style type=\"text/css\">h1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} h2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} h3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} body {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} b {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} p {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;} a {color:black;} a.name {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 405 – Method Not Allowed</h1><hr class=\"line\" /><p><b>Type</b> Status Report</p><p><b>Message</b> Request method &#39;POST&#39; not supported</p><p><b>Description</b> The method received in the request-line is known by the origin server but not supported by the target resource.</p><hr class=\"line\" /><h3>Apache Tomcat/8.5.37</h3></body></html>"

### PR DESCRIPTION
**Pull request by nblagoev**
### Description

Support executing the 'Run Action' command against vRO 7.6 and 8.0

### Checklist

- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] I have tested against live vRO/vRA, if applicable
- [x] My changes have been rebased and squashed to the minimal number of relevant commits
- [x] My changes have a descriptive commit message with a short title, including a `Fixed #XXX -` or `Closed #XXX -` prefix to auto-close the issue

### Testing

Tested against live (embedded) vRO 7.4, 7.6 and 8.0

### Related issues and PRs
#48

### CODE REVIEW

File: extension/src/client/command/RunAction.ts [hunk 1]
```diff
@@ -251,90 +307,165 @@ export class RunAction extends Command {
...
+        onError: (lineNumber: number, message: string) => void
+    ): FetchLogsStrategy {
+        if (semver.lt(this.vroVersion, "7.4.0")) {
+            return new FetchLogsPre74(onLog, onError, this.executionToken, this.restClient)
+        } else if (semver.lt(this.vroVersion, "7.6.0")) {
+            return new FetchLogsPre76(onLog, onError, this.executionToken, this.restClient)
         }
 
-        return state
+        return new FetchLogsPost76(onLog, onError, this.executionToken, this.restClient)
```
Comment (krisdimitrov) [inline extension/src/client/command/RunAction.ts]: What a nice granular API 😄
